#ifndef _R51_MONITOR_CONFIG_H_
#define _R51_MONITOR_CONFIG_H_

#define SERIAL_DEVICE Serial
#define SERIAL_BAUDRATE 115200
#define SERIAL_WAIT true

#define CAN_MODE Canny::CAN20_250K

#define DEBUG_ENABLE

#endif  // _R51_MONITOR_CONFIG_H_
